// Code generated by "stringer -type=Verb"; DO NOT EDIT.

package querybuilder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VerbRaw-0]
	_ = x[VerbCount-1]
	_ = x[VerbSum-2]
	_ = x[VerbAvg-3]
	_ = x[VerbMin-4]
	_ = x[VerbMax-5]
}

const _Verb_name = "VerbRawVerbCountVerbSumVerbAvgVerbMinVerbMax"

var _Verb_index = [...]uint8{0, 7, 16, 23, 30, 37, 44}

func (i Verb) String() string {
	if i < 0 || i >= Verb(len(_Verb_index)-1) {
		return "Verb(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verb_name[_Verb_index[i]:_Verb_index[i+1]]
}
